apiVersion: v2
description: Deploy components for aad-pod-identity
name: aad-pod-identity
version: 4.1.0
appVersion: 1.8.0
home: https://github.com/Azure/aad-pod-identity
sources:
  - https://github.com/Azure/aad-pod-identity
maintainers:
  - name: aramase
    email: anish.ramasekar@gmail.com
