apiVersion: v1
description: Deploy components for aad-pod-identity
name: aad-pod-identity
version: 1.5.6
appVersion: 1.5.5
home: https://github.com/Azure/aad-pod-identity
sources:
  - https://github.com/Azure/aad-pod-identity
maintainers:
  - name: aramase
    email: anish.ramasekar@gmail.com
