# Default values for aad-pod-identity-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository: mcr.microsoft.com/k8s/aad-pod-identity
  imagePullPolicy: Always

# https://github.com/Azure/aad-pod-identity#4-optional-match-pods-in-the-namespace
# By default, AAD Pod Identity matches pods to identities across namespaces.
# To match only pods in the namespace containing AzureIdentity set this to true.
forceNameSpaced: "false"

# When NMI runs on a node where MIC is running, then MIC token request call is also
# intercepted by NMI. MIC can't get a valid token as to initialize and then
# assign the identity. Installing an exception for MIC would ensure all token requests
# for MIC pods directly go to IMDS and not go through the pod-identity validation
# https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.app-exception.md
installMICException: "true"

## If using a separate service principal for aad-pod-identity instead of cluster service principal specify the following
## (The chart will perform the base64 encoding for you for values that are stored in secrets.)
adminsecret: {}
#   cloud: <cloud environment name>
#   subscriptionID: <subscription id>
#   resourceGroup: <cluster resource group>
#   vmType: <`standard` for normal virtual machine nodes, and `vmss` for cluster deployed with a virtual machine scale set>
#   tenantID: <service principal tenant id>
#   clientID: <service principal client id>
#   clientSecret: <service principal client secret>

# Operation mode for pod-identity. Default is standard mode that has MIC doing identity assignment
# Allowed values: "standard", "managed"
operationMode: "standard"

mic:
  image: mic
  tag: 1.6.0

  priorityClassName: ""

  # log level. Uses V logs (glog)
  logVerbosity: 0

  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi

  podAnnotations: {}

  ## Node labels for pod assignment
  ## aad-pod-identity is currently only supported on linux
  nodeSelector:
    beta.kubernetes.io/os: linux

  tolerations: []

  affinity: {}

  leaderElection:
    # Override leader election instance name (default is 'hostname')
    instance: ""
    # Override the namespace to create leader election objects (default is default namespace)
    namespace: ""
    # Override leader election name (default is aad-pod-identity-mic)
    name: ""
    # Override leader election duration (default is 15s)
    duration: ""

  # Override http liveliness probe port (default is 8080)
  probePort: ""

  # Override interval in seconds at which sync loop should periodically check for errors and reconcile (default is 3600s)
  syncRetryDuration: ""

  # Override the defult value of immutable identities.
  immutableUserMSIs: []
    # Example of MSIs (should be replaced with the real client ids)
    #- "00000000-0000-0000-0000-000000000000"
    #- "11111111-1111-1111-1111-111111111111"

  # https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.featureflags.md#batch-create-delete-flag
  # default value is 20
  createDeleteBatch: ""

  # https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.featureflags.md#client-qps-flag
  # default value is 5
  clientQps: ""

  # default value is 8888
  # prometheus port for metrics
  prometheusPort: ""

  # cloud configuration used to authenticate with Azure
  cloudConfig: "/etc/kubernetes/azure.json"

nmi:
  image: nmi
  tag: 1.6.0

  priorityClassName: ""

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  podAnnotations: {}

  ## Node labels for pod assignment
  ## aad-pod-identity is currently only supported on linux
  nodeSelector:
    beta.kubernetes.io/os: linux

  tolerations: []

  affinity: {}

  # Override iptables update interval in seconds (default is 60)
  ipTableUpdateTimeIntervalInSeconds: ""

  # Override mic namespace to short circuit MIC token requests (default is default namespace)
  micNamespace: ""

  # Override http liveliness probe port (default is 8080)
  probePort: ""

  # Override number of retries in NMI to find assigned identity in CREATED state (default is 16)
  retryAttemptsForCreated: ""

  # Override number of retries in NMI to find assigned identity in ASSIGNED state (default is 4)
  retryAttemptsForAssigned: ""

  # Override retry interval to find assigned identities in seconds (default is 5)
  findIdentityRetryIntervalInSeconds: ""

  # Enable scale features - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.featureflags.md#enable-scale-features-flag
  # Accepted values are true/false. Default is false.
  enableScaleFeatures: ""

  # default value is 9090
  # prometheus port for metrics
  prometheusPort: ""

  # https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.featureflags.md#block-instance-metadata-flag
  # default is false
  blockInstanceMetadata: ""

  # https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.featureflags.md#metadata-header-required-flag
  # default is false
  metadataHeaderRequired: ""

rbac:
  enabled: true
  # NMI requires permissions to get secrets when service principal (type: 1) is used in AzureIdentity.
  # If using only MSI (type: 0) in AzureIdentity, secret get permission can be disabled by setting this to false.
  allowAccessToSecrets: true

# Create azure identities and bindings
azureIdentities: []
  # - name: "azure-identity"
  #   # if not defined, then the azure identity will be deployed in the same namespace as the chart
  #   namespace: ""
  #   # type 0: MSI, type 1: Service Principal
  #   type: 0
  #   # /subscriptions/subscription-id/resourcegroups/resource-group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name
  #   resourceID: ""
  #   clientID: ""
  #   binding:
  #     name: "azure-identity-binding"
  #     # The selector will also need to be included in labels for app deployment
  #     selector: "demo"
