apiVersion: v1
entries:
  aad-pod-identity:
  - apiVersion: v1
    appVersion: 1.6.2
    created: "2020-07-24T14:28:04.610381-07:00"
    description: Deploy components for aad-pod-identity
    digest: 01245ef2726b40c098d56856f16eb868fc7ea226190a4f3f072c2ecec857fccb
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-2.0.1.tgz
    version: 2.0.1
  - apiVersion: v1
    appVersion: 1.6.1
    created: "2020-07-24T14:28:04.609238-07:00"
    description: Deploy components for aad-pod-identity
    digest: 2f1a2cdd4b89a93bca6e5e14cc4f701f6f9b774b51cbfdd5ca269c1be0c455af
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    appVersion: 1.6.0
    created: "2020-07-24T14:28:04.608137-07:00"
    description: Deploy components for aad-pod-identity
    digest: 7753d4ca3f27f2abcf7def0733c8b3543483266435a2fb3b038b254385a1ef19
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.6.0.tgz
    version: 1.6.0
  - apiVersion: v1
    appVersion: 1.5.5
    created: "2020-07-24T14:28:04.60689-07:00"
    description: Deploy components for aad-pod-identity
    digest: 8cd12b380d1ae694d0c916409cd6747572f80e83bdbfec7ce806a496da37aa07
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.5.6.tgz
    version: 1.5.6
  - apiVersion: v1
    appVersion: 1.5.5
    created: "2020-07-24T14:28:04.605475-07:00"
    description: Deploy components for aad-pod-identity
    digest: a35ceab66397ef58df6b60cb446445e68baaced1d7526690896dcfba21758abb
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.5.5.tgz
    version: 1.5.5
  - apiVersion: v1
    appVersion: 1.5.4
    created: "2020-07-24T14:28:04.604594-07:00"
    description: Deploy components for aad-pod-identity
    digest: b04a1510d3bb0f9afb5e3f7a9ba9af313027615cbb6d480050b992423819e13f
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.5.4.tgz
    version: 1.5.4
  - apiVersion: v1
    appVersion: 1.5.3
    created: "2020-07-24T14:28:04.603611-07:00"
    description: Deploy components for aad-pod-identity
    digest: 3dab91c7f115d23123f863eeea1c93a34640a42ac1e7052600020600fbfa55ad
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.5.3.tgz
    version: 1.5.3
  - apiVersion: v1
    appVersion: 1.5.2
    created: "2020-07-24T14:28:04.601707-07:00"
    description: Deploy components for aad-pod-identity
    digest: 58a8ea212a1461f72ce17be5b767dac920d0f56803c026320a16c22de3ed365a
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.5.2.tgz
    version: 1.5.2
generated: "2020-07-24T14:28:04.600208-07:00"
