apiVersion: v1
entries:
  aad-pod-identity:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2021-05-10T11:19:27.765012-07:00"
    description: Deploy components for aad-pod-identity
    digest: 52b431f446e8b5af2cf22e959c7d93b0dd02e162d8f7b1c859fcb000e2cfe6da
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-4.1.0.tgz
    version: 4.1.0
  - apiVersion: v2
    appVersion: 1.7.5
    created: "2021-04-02T09:41:37.500254-07:00"
    description: Deploy components for aad-pod-identity
    digest: 7dc3d7ae51b1d73583b752d1ea3f69d42509fa10325ee129e604378df21dda51
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-4.0.0.tgz
    version: 4.0.0
  - apiVersion: v1
    appVersion: 1.7.4
    created: "2021-02-11T11:05:49.087541-08:00"
    description: Deploy components for aad-pod-identity
    digest: ea67168c50976a87b95f46076d0dcaca5653f2e80edc4beca3e88854124c5104
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-3.0.3.tgz
    version: 3.0.3
  - apiVersion: v1
    appVersion: 1.7.3
    created: "2021-02-05T11:36:16.985046-08:00"
    description: Deploy components for aad-pod-identity
    digest: 6de5b895721992bfdc2ab521dd343ec49dd6cd38d53e1e8db702bdd66e170bf0
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-3.0.2.tgz
    version: 3.0.2
  - apiVersion: v1
    appVersion: 1.7.2
    created: "2021-02-02T11:32:04.401348-08:00"
    description: Deploy components for aad-pod-identity
    digest: f56691eff8703d1204718b9ddc94ce922d83ca1fbe9245e66f33dc5d8e10015c
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-3.0.1.tgz
    version: 3.0.1
  - apiVersion: v1
    appVersion: 1.7.1
    created: "2020-12-15T14:48:11.083624-08:00"
    description: Deploy components for aad-pod-identity
    digest: 0f31fa4e18cb1f4abcea02de735d983fd83bee02b5cba933920cc3a85a789734
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-3.0.0.tgz
    version: 3.0.0
  - apiVersion: v1
    appVersion: 1.7.0
    created: "2020-11-30T11:03:39.554704-08:00"
    description: Deploy components for aad-pod-identity
    digest: d73eada64c3c55df9452ebfb1b209bf372103f061b438c457c73346e21bc3143
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v1
    appVersion: 1.6.3
    created: "2020-11-30T11:03:39.552219-08:00"
    description: Deploy components for aad-pod-identity
    digest: 15cba678cddc2f4a2d7c9367167076f16d51fb28ad239936d38303647a52ddcc
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-2.0.2.tgz
    version: 2.0.2
  - apiVersion: v1
    appVersion: 1.6.2
    created: "2020-11-30T11:03:39.550404-08:00"
    description: Deploy components for aad-pod-identity
    digest: 01245ef2726b40c098d56856f16eb868fc7ea226190a4f3f072c2ecec857fccb
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-2.0.1.tgz
    version: 2.0.1
  - apiVersion: v1
    appVersion: 1.6.1
    created: "2020-11-30T11:03:39.548995-08:00"
    description: Deploy components for aad-pod-identity
    digest: 2f1a2cdd4b89a93bca6e5e14cc4f701f6f9b774b51cbfdd5ca269c1be0c455af
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    appVersion: 1.6.0
    created: "2020-11-30T11:03:39.547562-08:00"
    description: Deploy components for aad-pod-identity
    digest: 7753d4ca3f27f2abcf7def0733c8b3543483266435a2fb3b038b254385a1ef19
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.6.0.tgz
    version: 1.6.0
  - apiVersion: v1
    appVersion: 1.5.5
    created: "2020-11-30T11:03:39.546102-08:00"
    description: Deploy components for aad-pod-identity
    digest: 8cd12b380d1ae694d0c916409cd6747572f80e83bdbfec7ce806a496da37aa07
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.5.6.tgz
    version: 1.5.6
  - apiVersion: v1
    appVersion: 1.5.5
    created: "2020-11-30T11:03:39.54453-08:00"
    description: Deploy components for aad-pod-identity
    digest: a35ceab66397ef58df6b60cb446445e68baaced1d7526690896dcfba21758abb
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.5.5.tgz
    version: 1.5.5
  - apiVersion: v1
    appVersion: 1.5.4
    created: "2020-11-30T11:03:39.543456-08:00"
    description: Deploy components for aad-pod-identity
    digest: b04a1510d3bb0f9afb5e3f7a9ba9af313027615cbb6d480050b992423819e13f
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.5.4.tgz
    version: 1.5.4
  - apiVersion: v1
    appVersion: 1.5.3
    created: "2020-11-30T11:03:39.542333-08:00"
    description: Deploy components for aad-pod-identity
    digest: 3dab91c7f115d23123f863eeea1c93a34640a42ac1e7052600020600fbfa55ad
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.5.3.tgz
    version: 1.5.3
  - apiVersion: v1
    appVersion: 1.5.2
    created: "2020-11-30T11:03:39.541214-08:00"
    description: Deploy components for aad-pod-identity
    digest: 58a8ea212a1461f72ce17be5b767dac920d0f56803c026320a16c22de3ed365a
    home: https://github.com/Azure/aad-pod-identity
    maintainers:
    - email: anish.ramasekar@gmail.com
      name: aramase
    name: aad-pod-identity
    sources:
    - https://github.com/Azure/aad-pod-identity
    urls:
    - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-1.5.2.tgz
    version: 1.5.2
generated: "2021-05-10T11:19:27.761378-07:00"
